### PR TITLE
TimeSeries API Implementation

### LINKED ISSUE #2: Implement TimeSeries service
### TimeSeries API

A TimeSeries is a special purpose extension of the existing TreeMap class where the key type parameter is always Integer, and the value type parameter is always Double. Each key will correspond to a year, and each value a numerical data point for that year. 

For example, the following code would create a TimeSeries and associate the year 1992 with the value 3.6 and 1993 with 9.2.
```java
TimeSeries ts = new TimeSeries();
ts.put(1992,3.6);
ts.put(1993,9.2);
```
The TimeSeries class provides some additional utility API to the TreeMap class, which it extends. i.e. 

`plus (TimeSeries ts)` which returns the year-wise sum of this TimeSeries with the given TS. If both TimeSeries don't contain any years, return an empty TimeSeries. If one TimeSeries contains a year that the other one doesn't, the returned TimeSeries should store the value from the TimeSeries that contains that year.

```java 
public TimeSeries plus(TimeSeries ts);
```

`dividedBy(TimeSeries ts)` which returns the quotient of the value for each year this TimeSeries divided by the value for the same year in TS. Should return a new TimeSeries (does not modify this TimeSeries). If TS is missing a year that exists in this TimeSeries, throw an IllegalArgumentException. If TS has a year that is not in this TimeSeries, ignore it.

```java
public TimeSeries dividedBy(TimeSeries ts);
```

### Note:
- TimeSeries objects should have no instance variables. 
- You may assume that the dividedBy operation never divides by zero.
- Several methods require that you compare the data of two TimeSeries. You should not have any code which fills in a zero if a year or value is unavailable.

Related to #1

### PR DESCRIPTION
**Pull request by s-bose7**
Fix #2 

A TimeSeries is a special purpose extension of the existing TreeMap class for utility services.

### CODE REVIEW

File: src/main/java/com/ngram/app/services/TimeSeries.java [hunk 1]
```diff
@@ -29,24 +32,26 @@ public TimeSeries() {
      */
     public TimeSeries(TimeSeries ts, int startYear, int endYear) {
         super();
-        // TODO: Fill in this constructor.
+        for(int year=startYear; year<=endYear; year++) {
+        	if(ts.containsKey(year)) { 
+        		this.put(year, ts.get(year)); 
+        	}
+        }
     }
```
Comment (s-bose7) [inline src/main/java/com/ngram/app/services/TimeSeries.java:40]: Another consideration would be to traverse the this TimeSeries directly using `Map.Entry<Integer, Double>` iterator, and only if the following condition statisfied (startYear <= `entry.getKey()` <= endYear), we do a put operation to this TimeSeries.
